### ISSUE TITLE
Remove html tag on post preview (excerpt)

### ISSUE THREAD

**Issue by achmatch** [stephenjude/lite-blog#11]
Everytime post an article there is always showing raw html on post excerpt, but not on full post.

**Comment by stephenjude** [comment]
Can you send a screnshot of where you're displaying the post on your blade file. @achmatch

**Comment by achmatch** [comment]
im using snippet on my blade template.
`$post->body, 250`

This is screenshot on post excerpt
=====================
![Screenshot_20210527-151830_Chrome](https://user-images.githubusercontent.com/8610063/119783031-67a90480-beff-11eb-93cc-1a69d4871a32.jpg)
=====================
And work fine on full post.
=====================
![Screenshot_20210527-151918_Chrome](https://user-images.githubusercontent.com/8610063/119783194-932bef00-beff-11eb-97b0-db7cc708c87e.jpg)

**Comment by stephenjude** [comment]
enclose it inside this tag` {!! $post->body !!}`

**Comment by achmatch** [comment]
I know.
But still got raw html on post excerpt.

**Comment by stephenjude** [comment]
Post excerpts are plain text but you can use the same method above to fix it.
